export const project_dummy = [
  {
    id: 1,
    title: "Proyek Redesign E-Commerce Mobile",
    category: "UI/UX",
    date: "12 jun 2025",
    publisher: "Dani Setiawan",
    stars: "5",
    status: "Published",
  },
  {
    id: 2,
    title: "Studi Kasus Accessibility Web App",
    category: "UI/UX",
    date: "9 nov 2023",
    publisher: "Dani Setiawan",
    stars: "4",
    status: "Denied",
  },
  {
    id: 3,
    title: "Pengembangan Game Edukasi Anak",
    category: "Game",
    date: "15 aug 2024",
    publisher: "Dani Setiawan",
    stars: "0",
    status: "Review",
  },
  {
    id: 4,
    title: "Sistem Informasi Manajemen Lab",
    category: "Web",
    date: "20 dec 2023",
    publisher: "Dani Setiawan",
    stars: "3",
    status: "Muted",
  },
];

export const news_dummy = [
  {
    id: 1,
    title: "Workshop Keamanan Siber",
    category: "Workshops",
    date: "30 jan 2025",
    publisher: "Dani Setiawan",
    status: "Published",
  },
  {
    id: 2,
    title: "Pelatihan React JS Dasar",
    category: "Training",
    date: "15 feb 2025",
    publisher: "Dani Setiawan",
    status: "Waiting",
  },
  {
    id: 3,
    title: "Sertifikasi AI untuk Pendidikan",
    category: "Certifications",
    date: "10 mar 2025",
    publisher: "Dani Setiawan",
    status: "Review",
  },
  {
    id: 4,
    title: "Artikel Teknologi Blockchain",
    category: "Articles",
    date: "05 apr 2025",
    publisher: "Dani Setiawan",
    status: "Muted",
  },
];

export const gallery_dummy = [
  {
    id: 1,
    title: "Open Recruitment Lab MMT ",
    photo: "50",
    video: "68",
    animation: "34",
    date: "31 Aug 2025",
    publisher: "Budi Santoso",
    status: "Review",
  },
  {
    id: 2,
    title: "Game Jam MMC",
    photo: "12",
    video: "30",
    animation: "15",
    date: "15 Sep 2025",
    publisher: "Citra Dewi",
    status: "Published",
  },
  {
    id: 3,
    title: "Play IT Polinema 2025",
    photo: "90",
    video: "110",
    animation: "55",
    date: "05 Oct 2024",
    publisher: "Andi Wijaya",
    status: "Draft",
  },
  {
    id: 4,
    title: "11th Dies Natalis",
    photo: "35",
    video: "42",
    animation: "20",
    date: "22 Oct 2023",
    publisher: "Dewi Lestari",
    status: "Published",
  },
  {
    id: 5,
    title: "Workshop Game Unity",
    photo: "60",
    video: "75",
    animation: "40",
    date: "10 Nov 2025",
    publisher: "Eko Prasetyo",
    status: "Review",
  },
];

export const member_dummy = [
  {
    name: "Aulia Resty Azizah",
    identityNum: "244107020015",
    role: "Game Developer",
    startDate: "31 Agustus 2025",
    position: "Researcher",
  },
  {
    name: "Resty Azizah",
    identityNum: "244107020015",
    role: "Frontend Developer",
    startDate: "1 Agustus 2025",
    position: "Researcher",
  },
  {
    name: "Budi Budi arto",
    identityNum: "244107020015",
    role: "UI/UX Designer",
    startDate: "31 Mei 2025",
    position: "Researcher",
  },
  {
    name: "Lando Norris",
    identityNum: "244107020015",
    role: "Frontend Developer",
    startDate: "31 Agustus 2023",
    position: "Researcher",
  },
  {
    name: "Marc marquez",
    identityNum: "244107020015",
    role: "UI/UX Designer",
    startDate: "20 Agustus 2025",
    position: "Researcher",
  },
  {
    name: "Muhammad Wahyu",
    identityNum: "244107020015",
    role: "UI/UX Designer",
    startDate: "31 Agustus 2024",
    position: "Researcher",
  },
  {
    name: "Fidela",
    identityNum: "244107020015",
    role: "Game Developer",
    startDate: "5 Agustus 2025",
    position: "Researcher",
  },
];

export const registration_dummy = [
  {
    id: 1,
    name: "Budi Santoso",
    nim: "244107020001",
    email: "budi@email.com",
    role: "Frontend Developer",
    cvUrl: "/cv/budi.pdf",
    ktmUrl: "/ktm/budi.pdf",
    registrationDate: "2024-11-30",
    status: "pending",
    document: "budi_document.pdf",
  },
];
