import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("members/slug/:slug", "routes/detailteam-member.tsx"),
    route("project", "routes/project.tsx"),
    route("project/slug/:slug", "routes/project-detail.tsx"),
    route("preview-project/:id", "routes/preview-project.tsx"),
    route("gallery", "routes/gallery.tsx"),
    route("news", "routes/news.tsx"),
    route("news/slug/:slug", "routes/news-detail.tsx"),
    route("sign-in", "routes/masuk.tsx"),
    route("profil", "routes/profil.tsx"),
    route("dashboard-viewer", "routes/dashboard-viewer/dashboard.tsx"),
    route("dashboard-viewer-news", "routes/dashboard-viewer/news.tsx"),
    route("dashboard-viewer-project", "routes/dashboard-viewer/project.tsx"),
    route("dashboard-viewer-gallery", "routes/dashboard-viewer/gallery.tsx"),
    route("dashboard-viewer-member", "routes/dashboard-viewer/member.tsx"),
    route("dashboard-lecturer", "routes/dashboard-lecturer/dashboard.tsx"),
    route("dashboard-student", "routes/dashboard-student/dashboard.tsx"),
    route("dashboard-student-news", "routes/dashboard-student/news.tsx"),
    route("dashboard-student-project", "routes/dashboard-student/project.tsx"),
    route("dashboard-student-gallery", "routes/dashboard-student/gallery.tsx"),
    route("dashboard-student-member", "routes/dashboard-student/member.tsx"),
    route("dashboard-lecturer-news", "routes/dashboard-lecturer/news.tsx"),
    route("dashboard-lecturer-project", "routes/dashboard-lecturer/project.tsx"),
    route("dashboard-lecturer-gallery", "routes/dashboard-lecturer/gallery.tsx"),
    route("dashboard-lecturer-member", "routes/dashboard-lecturer/member.tsx"),
    route("dashboard-admin", "routes/dashboard-admin/dashboard.tsx"),
    route("dashboard-admin-news", "routes/dashboard-admin/news.tsx"),
    route("dashboard-admin-project", "routes/dashboard-admin/project.tsx"),
    route("dashboard-admin-gallery", "routes/dashboard-admin/gallery.tsx"),
    route("dashboard-admin-member", "routes/dashboard-admin/member.tsx"),
    
] satisfies RouteConfig;
