  export const projects = [
    {
      image: "/proyek/images.jpg",
      date: "11 Nov 2025",
      title: "Project A",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      tags: ["Unity"],
      info: "Game",
    },
    {
      image: "/proyek/images.png",
      date: "11 Nov 2025",
      title: "Project B",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      tags: ["Tailwind", "React"],
      info: "UI/UX",
    },
    {
      image: "/proyek/ar.jpg",
      date: "11 Nov 2025",
      title: "Project C",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      tags: ["Tailwind", "Javascript"],
      info: "AR/VR",
    },
    {
      image: "/proyek/12.avif",
      date: "8 Nov 2024",
      title: "Project D",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      tags: ["Unity"],
      info: "AR/VR",
    },
    {
      image: "/proyek/12.avif",
      date: "10 Nov 2024",
      title: "Project E",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      tags: ["Figma"],
      info: "UI/UX",
    },
    {
      image: "/proyek/12.avif",
      date: "11 Nov 2024",
      title: "Project F",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      tags: ["Unity"],
      info: "AR/VR",
    },
  ];