export const news = [
    {
      image: "/galeri/eventA.jpg",
      date: "10 Nov 2024",
      title: "NEWS A",
      desc: "Kegiatan pelatihan AR/VR bersama anggota lab MMT.",
      tags: ["News", "Resty"],
      info: "Malang",
    },
    {
      image: "/galeri/eventB.jpg",
      date: "10 Nov 2024",
      title: "NEWS B",
      desc: "Menampilkan hasil karya mahasiswa berbasis Unity.",
      tags: ["Workshop", "Wahyu"],
      info: "Darjo",
    },
    {
      image: "/galeri/eventC.jpg",
      date: "10 Nov 2024",
      title: "NEWS C",
      desc: "Kegiatan kunjungan industri ke perusahaan teknologi.",
      tags: ["News", "Fidel"],
      info: "Blitar",
    },
    {
      image: "/galeri/eventA.jpg",
      date: "10 Nov 2024",
      title: "NEWS A",
      desc: "Kegiatan pelatihan AR/VR bersama anggota lab MMT.",
      tags: ["Workshop", "Excel"],
      info: "Malang",
    },
    {
      image: "/galeri/eventB.jpg",
      date: "10 Nov 2024",
      title: "NEWS B",
      desc: "Menampilkan hasil karya mahasiswa berbasis Unity.",
      tags: ["News", "Rizki"],
      info: "Darjo",
    },
    {
      image: "/galeri/eventC.jpg",
      date: "10 Nov 2024",
      title: "NEWS C",
      desc: "Kegiatan kunjungan industri ke perusahaan teknologi.",
      tags: ["Workshop", "Siti"],
      info: "Blitar",
    },
    {
      image: "/galeri/eventA.jpg",
      date: "10 Nov 2024",
      title: "NEWS A",
      desc: "Kegiatan pelatihan AR/VR bersama anggota lab MMT.",
      tags: ["News", "Marquez"],
      info: "Malang",
    },
    {
      image: "/galeri/eventB.jpg",
      date: "10 Nov 2024",
      title: "NEWS B",
      desc: "Menampilkan hasil karya mahasiswa berbasis Unity.",
      tags: ["Workshop", "Lando"],
      info: "Darjo",
    },
    {
      image: "/galeri/eventC.jpg",
      date: "10 Nov 2024",
      title: "NEWS C",
      desc: "Kegiatan kunjungan industri ke perusahaan teknologi.",
      tags: ["News", "Aulia"],
      info: "Blitar",
    },
    {
      image: "/galeri/eventA.jpg",
      date: "10 Nov 2024",
      title: "NEWS A",
      desc: "Kegiatan pelatihan AR/VR bersama anggota lab MMT.",
      tags: ["News", "Aulia Resty Azizah"],
      info: "Malang",
    },
    {
      image: "/galeri/eventB.jpg",
      date: "10 Nov 2024",
      title: "NEWS B",
      desc: "Menampilkan hasil karya mahasiswa berbasis Unity.",
      tags: ["Workshop", "Nama Penulis"],
      info: "Darjo",
    },
    {
      image: "/galeri/eventC.jpg",
      date: "10 Nov 2024",
      title: "NEWS C",
      desc: "Kegiatan kunjungan industri ke perusahaan teknologi.",
      tags: ["Workshop", "Nama Penulis"],
      info: "Blitar",
    },
  ];